FROM node:24-alpine

WORKDIR /app

ARG ENV
ARG PORT
ARG RPC_URL
ARG PROGRAM_ID
ARG MASTER_WALLET_PRIVATE_KEY
ARG DATABASE_URL
ARG MAIL_HOST
ARG MAIL_PORT
ARG MAIL_USER
ARG GMAIL_APP_PASSWORD

# Copy application files
COPY . /app

# Install dependencies
RUN yarn install --frozen-lockfile

# Build the application
RUN yarn build

# Expose the application port
EXPOSE 4000

ENV ENV=prod
ENV RPC_URL=${RPC_URL}
ENV PROGRAM_ID=${PROGRAM_ID}
ENV MASTER_WALLET_PRIVATE_KEY=${MASTER_WALLET_PRIVATE_KEY}
ENV DATABASE_URL=${DATABASE_URL}
ENV PORT=4000
ENV MAIL_HOST=${MAIL_HOST}
ENV MAIL_PORT=${MAIL_PORT}
ENV MAIL_USER=${MAIL_USER}
ENV GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}

# Start the application
ENTRYPOINT ["yarn", "start:prod"]
